### ISSUE TITLE
Async tasks escape the initialization phase.

### ISSUE THREAD

**Issue by mpavelka** [TeskaLabs/asab#51] opened 2019-04-06 08:24 UTC
Tasks that are created inside an "initialize" lifecycle methods of Application **(1)** and/or Service **(2)** objects escape the initialization phase. Examples below have been tried with `Python 3.6.7`

**1)** In this example with **Application object**, `do_sleep()` runs out of the scope of the init phase if called using `ensure_future()`:

```
import asab
import asyncio

class Application(asab.Application):

	def __init__(self):
		super().__init__()

	async def initialize(self):
		await self.do_sleep() # do_sleep happens during the init phase
		asyncio.ensure_future(self.do_sleep()) # do_sleep escapes the init phase

	async def do_sleep(self):
		print("Application: before sleep")
		await asyncio.sleep(2)
		print("Application: after sleep")

	async def main(self):
		print("MAIN!")
		self.stop()

def main():
	app = Application()
	app.run()

if __name__ == '__main__':
	main()

```

**2)** In this example with initialization of **Service object** it is so that `do_sleep()` doesn't run within the init phase in both cases - when called using `await` and/or when called using `ensure_future()`

```
import asab
import asyncio

class MyService(asab.Service):

	async def initialize(self, app):
		await self.do_sleep() # do_sleep() AND self.initialize() escape the init phase
		asyncio.ensure_future(self.do_sleep()) # do_sleep() escapes init phase

	async def do_sleep(self):
		print("MyService: before sleep")
		await asyncio.sleep(2)
		print("MyService: after sleep")


class Application(asab.Application):

	def __init__(self):
		super().__init__()
		MyService(self, "MyService")

	async def main(self):
		print("MAIN!")
		self.stop()

def main():
	app = Application()
	app.run()

if __name__ == '__main__':
	main()

```

**Comment by awichera** [comment] 2020-03-03 13:43
@ateska  Since init time separation was later relaxed again, application_states example does not work as intended. I would suggest to change or delete it.

**Comment by ateska** [comment] 2020-06-15 19:58
Ok, closing as "feature, not bug"

**Closed by ateska** 2020-06-15 19:58 UTC
Labels: bug
